export const ADD_TASK = 'ADD_TASK'
export const START_TASK = 'START_TASK'
export const FINISH_TASK = 'FINISH_TASK'
export const SET_FILTER = 'SET_FILTER'

export const FilterTasks = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_TODO: 'SHOW_TODO',
  SHOW_IN_PROGRESS: 'SHOW_IN_PROGRESS',
  SHOW_COMPLETED: 'SHOW_COMPLETED'
}